<?php

/**
 * @file
 * Coffee primary module file.
 */

use Drupal\Core;

/**
 * Implements hook_permission().
 */
function coffee_permission() {
  return array(
    'access coffee' => array(
      'title' => t('Access Coffee'),
      'description' => t('Access the Coffee search box to navigate fast between admin pages'),
    ),
    'administer coffee' => array(
      'title' => t('Administer Coffee'),
      'description' => t('Administer the Coffee search module'),
    ),
  );
}

/**
 * Implements hook_menu_link_defaults().
 */
function coffee_menu_link_defaults() {
  $items['coffee.configuration'] = array(
    'link_title' => 'Coffee',
    'description' => 'Select what menus coffee should search.',
    'route_name' => 'coffee.configuration',
    'parent' => 'system.admin_config_ui',
  );
  return $items;
}

/**
 * Implements hook_page_build().
 */
function coffee_page_build(&$page) {
  // Access check.
  $account = \Drupal::currentUser();
  if ($account->hasPermission('access coffee')) {
    $page['#attached']['library'][] = 'coffee/drupal.coffee';
  }
}

/**
 * Implements hook_hook_info().
 */
function coffee_hook_info() {
  $hooks = array(
    'coffee_commands' => array(
      'group' => 'coffee',
    ),
  );
  return $hooks;
}
